# Generated by Django 5.2 on 2025-04-11 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='max_target_users',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_all_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_cities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_communes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_sex',
            field=models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='targeted_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, choices=[('abidjan', 'Abidjan'), ('bouake', 'Bouaké'), ('yamoussoukro', 'Yamoussoukro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commune',
            field=models.CharField(blank=True, choices=[('cocody', 'Cocody'), ('yopougon', 'Yopougon'), ('abobo', 'Abobo')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme')], max_length=10, null=True),
        ),
    ]
