# Generated by Django 5.2 on 2025-04-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_advertisement_max_target_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='target_address_keywords',
            field=models.TextField(blank=True, help_text="Mots-clés extraits de l'adresse.", null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rayon en kilomètres autour de la position ciblée.', max_digits=5, null=True),
        ),
    ]
