# Generated by Django 5.2 on 2025-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_advertisement_target_address_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='target_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='target_longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
