# Generated by Django 5.2 on 2025-04-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_advertisement_target_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='visits_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('visit', 'Visit')], max_length=10),
        ),
    ]
