# Generated by Django 5.2 on 2025-04-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_advertisement_visits_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, choices=[('lubumbashi', 'Lubumbashi'), ('likasi', 'Likasi'), ('kolwezi', 'Kolwezi'), ('kasumbalesa', 'Kasumbalesa'), ('kalemie', 'Kalemie'), ('kamina', 'Kamina'), ('kinshasa', 'Kinshasa'), ('kisangani', 'Kisangani'), ('mbujimayi', 'Mbujimayi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='commune',
            field=models.CharField(blank=True, choices=[('lubumbashi', 'Lubumbashi'), ('annexe', 'Annexe'), ('kenya', 'Kenya'), ('katuba', 'Katuba'), ('rwashi', 'Rwashi'), ('kampemba', 'Kampemba'), ('kamalondo', 'Kamalondo')], max_length=50, null=True),
        ),
    ]
