# Generated by Django 5.2 on 2025-04-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_store_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('visit', 'Visit'), ('bonus_1_point', 'Bonus 1 Point')], max_length=16),
        ),
    ]
