# Generated by Django 5.2 on 2025-04-17 09:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_adinteraction_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointconversion',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00143'), max_digits=5),
        ),
    ]
