# Generated by Django 5.2 on 2025-04-29 10:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pointconversion_conversion_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointconversion',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00125'), max_digits=5),
        ),
    ]
