# Generated by Django 5.2 on 2025-05-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_pointconversion_conversion_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si désactivé, la pub ne sera plus affichée.'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='max_likes',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre maximum de likes autorisé avant désactivation.', null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='max_shares',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
