# Generated by Django 5.2 on 2025-05-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_advertisement_is_active_advertisement_max_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupadvertisement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
